# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-03-30 15:56
from __future__ import unicode_literals

from django.db import migrations, models
import imagekit.models.fields
import users.models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0003_user_publisher'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='profile_pic',
            field=models.ImageField(default=None, null=True, upload_to=users.models.profile_pic_path),
        ),
        migrations.AddField(
            model_name='user',
            name='profile_pic_thumbnail',
            field=imagekit.models.fields.ProcessedImageField(default=None, null=True, upload_to=users.models.profile_pic_path),
        ),
    ]
