# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-07-28 16:14
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0004_auto_20170330_1556'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='age',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='user',
            name='name',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='user',
            name='native_langauge',
            field=models.CharField(choices=[(b'english', b'english'), (b'spanish', b'spanish')], default=b'english', max_length=20),
        ),
        migrations.AddField(
            model_name='user',
            name='secondary_language',
            field=models.CharField(choices=[(b'english', b'english'), (b'spanish', b'spanish')], default=b'spanish', max_length=20),
        ),
        migrations.AddField(
            model_name='user',
            name='subscription_type',
            field=models.CharField(choices=[(b'free', b'free'), (b'premium', b'premium'), (b'beta', b'beta')], default=b'free', max_length=20),
        ),
        migrations.AlterField(
            model_name='user',
            name='user_type',
            field=models.CharField(choices=[(b'publisher', b'publisher'), (b'staff', b'staff'), (b'reader', b'reader')], default=b'publisher', max_length=20),
        ),
    ]
