# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-03-02 22:17
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('publisher', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='publisher',
            name='name',
            field=models.CharField(max_length=30, unique=True),
        ),
    ]
