# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-03-07 21:09
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('publisher', '0002_auto_20170302_2217'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='publisher',
            name='users',
        ),
    ]
