# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-03-08 17:43
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('publisher', '0004_book'),
    ]

    operations = [
        migrations.AddField(
            model_name='book',
            name='misc',
            field=models.CharField(default=b'', max_length=50),
        ),
    ]
