# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-03-08 17:56
from __future__ import unicode_literals

from django.db import migrations
import imagekit.models.fields
import publisher.models


class Migration(migrations.Migration):

    dependencies = [
        ('publisher', '0005_book_misc'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='book',
            name='misc',
        ),
        migrations.AddField(
            model_name='book',
            name='avatar_thumbnail',
            field=imagekit.models.fields.ProcessedImageField(default=None, null=True, upload_to=publisher.models.book_image_path),
        ),
    ]
