# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-03-08 19:12
from __future__ import unicode_literals

from django.db import migrations, models
import publisher.models


class Migration(migrations.Migration):

    dependencies = [
        ('publisher', '0009_bookimage_bookpage'),
    ]

    operations = [
        migrations.AlterField(
            model_name='book',
            name='cover_image',
            field=models.ImageField(default=None, null=True, upload_to=publisher.models.book_cover_path),
        ),
    ]
