# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-03-08 20:36
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('publisher', '0010_auto_20170308_1912'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='bookpage',
            name='content',
        ),
        migrations.RemoveField(
            model_name='bookpage',
            name='layout',
        ),
    ]
