# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-03-08 20:37
from __future__ import unicode_literals

import django.contrib.postgres.fields.jsonb
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('publisher', '0011_auto_20170308_2036'),
    ]

    operations = [
        migrations.AddField(
            model_name='bookpage',
            name='content',
            field=django.contrib.postgres.fields.jsonb.JSONField(default=None, null=True),
        ),
    ]
