# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-03-16 21:01
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('publisher', '0013_auto_20170313_1441'),
    ]

    operations = [
        migrations.AddField(
            model_name='bookpage',
            name='order',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='book',
            name='publisher',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='books', to='publisher.Publisher'),
        ),
    ]
