# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-03-21 19:19
from __future__ import unicode_literals

import django.contrib.postgres.fields.jsonb
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('publisher', '0014_auto_20170316_2101'),
    ]

    operations = [
        migrations.AddField(
            model_name='bookpage',
            name='tagging_progress',
            field=django.contrib.postgres.fields.jsonb.JSONField(default=None, null=True),
        ),
    ]
