# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-03-21 19:24
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('publisher', '0015_bookpage_tagging_progress'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='bookpage',
            name='tagging_progress',
        ),
    ]
