# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-03-28 18:18
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('publisher', '0017_bookpage_tagging_progress'),
    ]

    operations = [
        migrations.CreateModel(
            name='BookComment',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('subject', models.CharField(max_length=300)),
                ('message', models.TextField()),
                ('status', models.CharField(choices=[(b'open', b'open'), (b'closed', b'closed')], default=b'open', max_length=50)),
                ('type', models.CharField(choices=[(b'suggestion', b'suggestion'), (b'warning', b'warning'), (b'error', b'error')], default=b'suggestion', max_length=50)),
                ('date_created', models.DateTimeField(auto_now_add=True)),
                ('book', models.ForeignKey(default=None, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='comments', to='publisher.Book')),
                ('page', models.ForeignKey(default=None, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='comments', to='publisher.BookPage')),
                ('parent_comment', models.ForeignKey(default=None, null=True, on_delete=django.db.models.deletion.CASCADE, to='publisher.BookComment')),
                ('read_by', models.ManyToManyField(to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
