# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-04-04 14:26
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('publisher', '0020_auto_20170330_1849'),
    ]

    operations = [
        migrations.AddField(
            model_name='book',
            name='author',
            field=models.CharField(default=b'', max_length=100),
        ),
    ]
