# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-04-04 20:39
from __future__ import unicode_literals

import django.contrib.postgres.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('publisher', '0021_book_author'),
    ]

    operations = [
        migrations.AddField(
            model_name='book',
            name='available_languages',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.CharField(choices=[(b'english', b'english'), (b'spanish', b'spanish')], max_length=40), default=list, size=None),
        ),
    ]
