# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-04-20 20:01
from __future__ import unicode_literals

import django.contrib.postgres.fields.jsonb
from django.db import migrations, models
import django.db.models.deletion
import publisher.models


class Migration(migrations.Migration):

    dependencies = [
        ('publisher', '0022_book_available_languages'),
    ]

    operations = [
        migrations.CreateModel(
            name='Translation',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('language', models.CharField(choices=[(b'english', b'english'), (b'spanish', b'spanish'), (b'french', b'french'), (b'italian', b'italian'), (b'russian', b'russian')], max_length=50)),
                ('status', models.CharField(choices=[(b'requested', b'requested'), (b'rejected', b'rejected'), (b'approved', b'approved'), (b'translation', b'translation'), (b'translation_review', b'translation_review'), (b'blend', b'blend'), (b'blend_review', b'blend_review'), (b'published', b'published')], max_length=50)),
                ('translation', models.FileField(default=None, null=True, upload_to=publisher.models.translation_path)),
                ('translation_review_progress', django.contrib.postgres.fields.jsonb.JSONField(default=list, null=True)),
                ('blends', models.FileField(default=None, null=True, upload_to=publisher.models.blend_path)),
                ('blend_review_progress', django.contrib.postgres.fields.jsonb.JSONField(default=list, null=True)),
                ('date_created', models.DateTimeField(auto_now_add=True)),
                ('date_approved', models.DateTimeField(default=None, null=True)),
                ('translation_start_time', models.DateTimeField(default=None, null=True)),
                ('translation_finish_time', models.DateTimeField(default=None, null=True)),
                ('translation_review_start_time', models.DateTimeField(default=None, null=True)),
                ('translation_review_finish_time', models.DateTimeField(default=None, null=True)),
                ('blend_start_time', models.DateTimeField(default=None, null=True)),
                ('blend_finish_time', models.DateTimeField(default=None, null=True)),
                ('blend_review_start_time', models.DateTimeField(default=None, null=True)),
                ('blend_review_finish_time', models.DateTimeField(default=None, null=True)),
                ('date_published', models.DateTimeField(default=None, null=True)),
                ('book', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='translation', to='publisher.Book')),
            ],
        ),
        migrations.RemoveField(
            model_name='bookpage',
            name='tagging_progress',
        ),
        migrations.AlterField(
            model_name='bookpage',
            name='content',
            field=django.contrib.postgres.fields.jsonb.JSONField(default={b'elements': [], b'style': {b'backgroundColor': b'#ffffff', b'flexDirection': b'column', b'padding': b'0px'}}, null=True),
        ),
    ]
