# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-04-28 15:44
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('publisher', '0023_auto_20170420_2001'),
    ]

    operations = [
        migrations.AddField(
            model_name='translation',
            name='blend_percentage',
            field=models.FloatField(default=0),
        ),
        migrations.AddField(
            model_name='translation',
            name='blend_status',
            field=models.CharField(choices=[(b'not started', b'not started'), (b'pending', b'pending'), (b'processing', b'processing'), (b'complete', b'complete')], default=b'not started', max_length=100),
        ),
        migrations.AlterField(
            model_name='bookcomment',
            name='type',
            field=models.CharField(choices=[(b'suggestion', b'suggestion'), (b'warning', b'warning'), ((b'translation',), (b'translation',))], default=b'suggestion', max_length=50),
        ),
        migrations.AlterField(
            model_name='translation',
            name='book',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='translations', to='publisher.Book'),
        ),
    ]
