# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-04-28 16:14
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('publisher', '0025_remove_translation_blend_percentage'),
    ]

    operations = [
        migrations.AddField(
            model_name='translation',
            name='blend_percentage',
            field=models.IntegerField(default=0),
        ),
    ]
