# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-05-04 19:56
from __future__ import unicode_literals

import django.contrib.postgres.fields.jsonb
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('publisher', '0026_translation_blend_percentage'),
    ]

    operations = [
        migrations.CreateModel(
            name='LayoutTemplate',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default=b'', max_length=100)),
                ('layout', django.contrib.postgres.fields.jsonb.JSONField(default={b'elements': [], b'style': {b'backgroundColor': b'#ffffff', b'flexDirection': b'column', b'padding': b'0px'}}, null=True)),
                ('publisher', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='templates', to='publisher.Publisher')),
            ],
        ),
    ]
