# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-05-05 18:52
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('publisher', '0027_layouttemplate'),
    ]

    operations = [
        migrations.AddField(
            model_name='book',
            name='template',
            field=models.ForeignKey(default=None, null=True, on_delete=django.db.models.deletion.CASCADE, to='publisher.LayoutTemplate'),
        ),
    ]
