# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-05-08 15:13
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('publisher', '0028_book_template'),
    ]

    operations = [
        migrations.AddField(
            model_name='book',
            name='ave_rating',
            field=models.FloatField(default=None, null=True),
        ),
    ]
