# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-05-08 16:17
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('publisher', '0030_bookdownload_bookrating'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bookrating',
            name='rating',
            field=models.FloatField(default=0),
        ),
    ]
