# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-05-08 16:32
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('publisher', '0031_auto_20170508_1617'),
    ]

    operations = [
        migrations.AddField(
            model_name='bookdownload',
            name='primary_language',
            field=models.CharField(default=None, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='bookdownload',
            name='secondary_language',
            field=models.CharField(default=None, max_length=50, null=True),
        ),
    ]
