"""
Django settings for polli project.

Generated by 'django-admin startproject' using Django 1.10.6.

For more information on this file, see
https://docs.djangoproject.com/en/1.10/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/1.10/ref/settings/
"""
import os

# Build paths inside the project like this: os.path.join(BASE_DIR, ...)
BASE_DIR = os.path.dirname(os.path.dirname(os.path.abspath(__file__)))


# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/1.10/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = 'ct*c23i%p(ois1&f5$0qp_)6r+&kh0w8az%a)6w3ir9)@#u7l='

# SECURITY WARNING: don't run with debug turned on in production!
DEBUG = False

ALLOWED_HOSTS = ['*']


# Application definition
INSTALLED_APPS = [
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',
    'storages',
    'widget_tweaks',
    'imagekit',
    'django.contrib.humanize',
    'rest_framework',
    'rest_framework.authtoken',
    'polli',
    'users',
    'publisher',
]

MIDDLEWARE = [
    'django.middleware.security.SecurityMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.middleware.common.CommonMiddleware',
    #'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
]

ROOT_URLCONF = 'polli.urls'
WSGI_APPLICATION = 'polli.wsgi.application'


# Database
# https://docs.djangoproject.com/en/1.10/ref/settings/#databases
DATABASES = {
    'default': {
        'ENGINE': 'django.db.backends.postgresql_psycopg2',
        'NAME': 'polli',
        'USER': 'aqueduct',
        'PASSWORD': 'tr4nscendent',
        'HOST': 'polli.cofb1qo28jw8.us-east-1.rds.amazonaws.com',
        'PORT': '5432',
    }
}


# Email Config
EMAIL_USE_SSL = True
EMAIL_HOST = 'smtp.sendgrid.net'
EMAIL_PORT = 465
EMAIL_HOST_USER = 'apikey'
EMAIL_HOST_PASSWORD = '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'
SENDGRID_API_KEY = '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'
DEFAULT_FROM_EMAIL = 'noreply@t19s.com'

ADMINS = [
    ('Steven Lorenzo', 'slorenzo@t19s.com'),
    ('Yoav Ilan', 'yilan@t19s.com'),
    ('Rotem Cohen', 'rcohen@t19s.com'),
    ('Eran Golden', 'egoldin@t19s.com'),
]

# Password validation
# https://docs.djangoproject.com/en/1.10/ref/settings/#auth-password-validators
LOGIN_URL = 'login'
LOGIN_REDIRECT_URL = 'login-complete'
LOGOUT_REDIRECT_URL = 'login'
AUTH_USER_MODEL = 'users.User'

AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
    },
]


# Internationalization
# https://docs.djangoproject.com/en/1.10/topics/i18n/
LANGUAGE_CODE = 'en-us'

TIME_ZONE = 'UTC'

USE_I18N = True

USE_L10N = True

USE_TZ = True


# Load Local Settings
try:
    from local_settings import *
except ImportError:
    print("No Local Settings File Found")


# AWS CONFIG
AWS_ACCESS_KEY_ID = 'AKIAIW3AIS65BRKAO6PQ'
AWS_SECRET_ACCESS_KEY = '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'
AWS_STORAGE_BUCKET_NAME = 'polli-static'
AWS_QUERYSTRING_AUTH = False
AWS_BUCKET_BASE_URL = 'https://s3.amazonaws.com/polli-static/'
AWS_SQS_NAME = 'awseb-e-8cvs3tamw3-stack-AWSEBWorkerQueue-7BH4831D130J'


# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/1.10/howto/static-files/
DEFAULT_FILE_STORAGE = 'storages.backends.s3boto3.S3Boto3Storage'
STATICFILES_STORAGE = 'django.contrib.staticfiles.storage.StaticFilesStorage' if DEBUG else 'storages.backends.s3boto3.S3Boto3Storage'
STATIC_URL = '/static/'


# Template Config
TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [],
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.debug',
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
            ],
        },
    },
]


# Rest Framework Config
REST_FRAMEWORK = {
    'DEFAULT_AUTHENTICATION_CLASSES': (
        'rest_framework.authentication.TokenAuthentication',
        'rest_framework.authentication.SessionAuthentication',
    ),
    'DEFAULT_PERMISSION_CLASSES': [
        'rest_framework.permissions.IsAuthenticated',
    ],
    'PAGE_SIZE': 50
}
